options:
  prev_tag: "versio-prev"
projects:
  - name: quiz-naturalisation
    id: 0
    root: "."
    tag_prefix: "v"
    tag_prefix_separator: ""
    version:
      file: "VERSION"
      pattern: '(\d+\.\d+\.\d+)'
    changelog:
      file: "CHANGELOG.md"
      template: "file:.versio/changelog.md.liquid"
commit:
  message: "chore(release): versio update versions"
sizes:
  use_angular: true
  fail:
    - "-"
